(function() {var implementors = {};
implementors["varisat"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"varisat/clause/alloc/struct.ClauseRef.html\" title=\"struct varisat::clause::alloc::ClauseRef\">ClauseRef</a>",synthetic:false,types:["varisat::clause::alloc::ClauseRef"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/clause/db/enum.Tier.html\" title=\"enum varisat::clause::db::Tier\">Tier</a>",synthetic:false,types:["varisat::clause::db::Tier"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/enum.ProofFormat.html\" title=\"enum varisat::ProofFormat\">ProofFormat</a>",synthetic:false,types:["varisat::proof::ProofFormat"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/prop/graph/enum.Reason.html\" title=\"enum varisat::prop::graph::Reason\">Reason</a>",synthetic:false,types:["varisat::prop::graph::Reason"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/prop/graph/enum.Conflict.html\" title=\"enum varisat::prop::graph::Conflict\">Conflict</a>",synthetic:false,types:["varisat::prop::graph::Conflict"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/state/enum.SatState.html\" title=\"enum varisat::state::SatState\">SatState</a>",synthetic:false,types:["varisat::state::SatState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat/variables/data/enum.SamplingMode.html\" title=\"enum varisat::variables::data::SamplingMode\">SamplingMode</a>",synthetic:false,types:["varisat::variables::data::SamplingMode"]},];
implementors["varisat_checker"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat_checker/clauses/enum.StoreClauseResult.html\" title=\"enum varisat_checker::clauses::StoreClauseResult\">StoreClauseResult</a>",synthetic:false,types:["varisat_checker::clauses::StoreClauseResult"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat_checker/clauses/enum.DeleteClauseResult.html\" title=\"enum varisat_checker::clauses::DeleteClauseResult\">DeleteClauseResult</a>",synthetic:false,types:["varisat_checker::clauses::DeleteClauseResult"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat_checker/variables/enum.SamplingMode.html\" title=\"enum varisat_checker::variables::SamplingMode\">SamplingMode</a>",synthetic:false,types:["varisat_checker::variables::SamplingMode"]},];
implementors["varisat_formula"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"varisat_formula/cnf/struct.CnfFormula.html\" title=\"struct varisat_formula::cnf::CnfFormula\">CnfFormula</a>",synthetic:false,types:["varisat_formula::cnf::CnfFormula"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"varisat_formula/lit/struct.Var.html\" title=\"struct varisat_formula::lit::Var\">Var</a>",synthetic:false,types:["varisat_formula::lit::Var"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"struct\" href=\"varisat_formula/lit/struct.Lit.html\" title=\"struct varisat_formula::lit::Lit\">Lit</a>",synthetic:false,types:["varisat_formula::lit::Lit"]},];
implementors["varisat_internal_proof"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html\" title=\"trait core::cmp::Eq\">Eq</a> for <a class=\"enum\" href=\"varisat_internal_proof/enum.DeleteClauseProof.html\" title=\"enum varisat_internal_proof::DeleteClauseProof\">DeleteClauseProof</a>",synthetic:false,types:["varisat_internal_proof::DeleteClauseProof"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
