(function() {var implementors = {};
implementors["varisat"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"varisat/prop/graph/enum.Conflict.html\" title=\"enum varisat::prop::graph::Conflict\">Conflict</a>&gt; for <a class=\"enum\" href=\"varisat/cdcl/enum.FoundConflict.html\" title=\"enum varisat::cdcl::FoundConflict\">FoundConflict</a>",synthetic:false,types:["varisat::cdcl::FoundConflict"]},];
implementors["varisat_formula"] = [{text:"impl&lt;Clauses, Item&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;Clauses&gt; for <a class=\"struct\" href=\"varisat_formula/cnf/struct.CnfFormula.html\" title=\"struct varisat_formula::cnf::CnfFormula\">CnfFormula</a> <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Clauses: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/iter/traits/collect/trait.IntoIterator.html\" title=\"trait core::iter::traits::collect::IntoIterator\">IntoIterator</a>&lt;Item = Item&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;Item: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/borrow/trait.Borrow.html\" title=\"trait core::borrow::Borrow\">Borrow</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">[</a><a class=\"struct\" href=\"varisat_formula/lit/struct.Lit.html\" title=\"struct varisat_formula::lit::Lit\">Lit</a><a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.slice.html\">]</a>&gt;,&nbsp;</span>",synthetic:false,types:["varisat_formula::cnf::CnfFormula"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"varisat_formula/lit/struct.Var.html\" title=\"struct varisat_formula::lit::Var\">Var</a>&gt; for <a class=\"struct\" href=\"varisat_formula/lit/struct.Lit.html\" title=\"struct varisat_formula::lit::Lit\">Lit</a>",synthetic:false,types:["varisat_formula::lit::Lit"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
